config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  
  resources :products

  devise_for :users
  resources :users, only: [:index, :show]

  resources :invoices
    get 'sales' => 'invoices#sales'
    get 'sales/draft' => 'invoices#sales_draft'
    get 'sales/legal' => 'invoices#sales_legal'
    get 'sales/cash' => 'invoices#sales_cash'
    get 'sales/credit' => 'invoices#sales_credit'
    post 'sales/sale' => 'invoices#sale'

    get 'purchases' => 'invoices#purchases'
    get 'purchases/draft' => 'invoices#purchases_draft'
    get 'purchases/legal' => 'invoices#purchases_legal'
    get 'purchases/cash' => 'invoices#purchases_cash'
    get 'purchases/credit' => 'invoices#purchases_credit'    
    
  resources :associateds do
    resources :invoices
  end
    get 'customers' => 'associateds#customers'
    get 'customers/recurrent' => 'associateds#customers_recurrent'
    get 'customers/punctual' => 'associateds#customers_punctual'
    get 'customers/active' => 'associateds#customers_active'
    get 'customers/inactive' => 'associateds#customers_inactive'
    get 'providers' => 'associateds#providers'
    get 'providers/recurrent' => 'associateds#providers_recurrent'
    get 'providers/punctual' => 'associateds#providers_punctual'
    get 'providers/active' => 'associateds#providers_active'
    get 'providers/inactive' => 'associateds#providers_inactive'
    get 'sponsors' => 'associateds#sponsors'
    get 'sponsors/recurrent' => 'associateds#sponsors_recurrent'
    get 'sponsors/punctual' => 'associateds#sponsors_punctual'
    get 'sponsors/active' => 'associateds#sponsors_active'
    get 'sponsors/inactive' => 'associateds#sponsors_inactive'

    

  
  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :associated
  belongs_to :user    
  belongs_to :product
  validates :quantity, :rate, :date, presence: true
  validates :description, length: { maximum: 150 }
  validates :name_product, length: { maximum: 30 }
  validates :document, length: { maximum: 150 }
  validates :payment_proof, length: { maximum: 150 }
  validates :rate, length: { maximum: 7 }
  validates :tax, length: { maximum: 12 }
  validates :quantity, numericality: { only_integer: true }
  validates :subtotal, length: { maximum: 12 }
  validates :total, length: { maximum: 12 } 
  validates :balance, length: { maximum: 12 } 
  validates :kind_payment, inclusion: { in: :kind_payment }
  validates :kind_operation, inclusion: { in: :kind_operation }
  validates :kind_invoice, inclusion: { in: :kind_invoice }
  enum kind_payment: [ :Cash, :Credit ]
  enum kind_operation: [ :Sale, :Purchase ]
  enum kind_invoice: [ :Draft, :Invoice ]

  def self.bill product, invoice, associated 
      quantity = invoice[:quantity].to_i
      rate = invoice[:rate].to_i
      balance = invoice[:balance].to_i
      subtotal = product.price*quantity
      tax = ((subtotal*rate)/100)
      total = (subtotal+tax)
      invoice[:name_associated] = associated.name
      invoice[:ci_associated] = associated.ci_rif
      invoice[:address_associated] = associated.address
      invoice[:name_product] = product.name
      invoice[:description] = product.description
      invoice[:subtotal] = subtotal
      invoice[:tax] = tax
      invoice[:total] = total
  end

  def self.change product, invoice, associated 
      quantity = invoice.quantity.to_i
      rate = invoice[:rate].to_i
      balance = invoice[:balance].to_i
      subtotal = product.price*quantity
      tax = ((subtotal*rate)/100)
      total = (subtotal+tax)
      invoice[:name_associated] = associated.name
      invoice[:ci_associated] = associated.ci_rif
      invoice[:address_associated] = associated.address
      invoice[:name_product] = product.name
      invoice[:description] = product.description
      invoice[:subtotal] = subtotal
      invoice[:tax] = tax
      invoice[:total] = total    
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate_user!
   prawnto :prawn => { :page_size => 'A4', :margin => 20 }

  def index
    @invoices = Invoice.all 
  end

  def show
    @invoice = []
    invoice = Invoice.find(params[:id]) 
    @invoice.push(invoice)  
    respond_to do |format|
      format.html
      format.pdf do
        pdf = InvoicePdf.new(@invoice)
        send_data pdf.render, filename: 'invoice.pdf', type: 'application/pdf'
      end
    end 
  end

  def new
    @invoice = Invoice.new   
  end

  def create
    invoice = Invoice.new(permit)
    product = Product.find(permit[:product_id])
    associated = Associated.find(permit[:associated_id])
    if Invoice.bill(product, invoice, associated)
      invoice.save
      redirect_to invoices_path, :notice => 'Bill Successfully Added.'
    else
      render 'new'
    end
  end

  def edit
    @invoice = Invoice.find(params[:id])
  end

  def update
    invoice = Invoice.find(params[:id])
    product = Product.find(permit[:product_id])
    associated = Associated.find(permit[:associated_id])
    if Invoice.change(product, invoice, associated)
      invoice.update(permit)
      if invoice.subtotal != product.price*invoice.quantity
        Invoice.change(product, invoice, associated)
      else
        invoice.update(permit)
      end
      invoice.update(permit)
      redirect_to invoices_path, :notice => 'Bill Successfully Added.'
    else
      render 'new'
    end
  end 

  def destroy    
    @invoice = Invoice.find(params[:id])
    if @invoice.kind_invoice == 'Draft'
      if @invoice.destroy
        redirect_to invoices_path, :notice => 'Draft Bill Successfully Deleted.'
      else
        render 'destroy'
      end
    else
      redirect_to invoices_path, :alert => 'The Invoice Should Not Be Deleted.'
    end
  end  

  def sales 
    @sales = Invoice.where(kind_operation: 0)
  end  

  def sales_draft 
    @sales = Invoice.where(kind_operation: 0, kind_invoice: 0)
  end  

  def sales_legal 
    @sales = Invoice.where(kind_operation: 0, kind_invoice: 1)
  end

  def sales_cash 
    @sales = Invoice.where(kind_operation: 0, kind_payment: 0)
  end

  def sales_credit 
    @sales = Invoice.where(kind_operation: 0, kind_payment: 1)
  end

  def purchases 
    @purchases = Invoice.where(kind_operation: 1)
  end

  def purchases_draft 
    @purchases = Invoice.where(kind_operation: 1, kind_invoice: 0)
  end

  def purchases_legal 
    @purchases = Invoice.where(kind_operation: 1, kind_invoice: 1)
  end

  def purchases_cash 
    @purchases = Invoice.where(kind_operation: 1, kind_payment: 0)
  end

  def purchases_credit 
    @purchases = Invoice.where(kind_operation: 1, kind_payment: 1)
  end  

  private

  def permit
    params.require(:invoice).permit(:kind_operation, :kind_payment, 
      :kind_invoice, :description, :name_product, :balance, :date, :quantity, 
      :tax, :rate, :document, :payment_proof, :associated_id, :user_id, 
      :product_id, :name_associated, :ci_associated, :address_associated)
  end
  
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/edit.html.erb
<div id="page-content-wrapper">
<div class="page-content inset">
  <div class="row">
      <div class="col-md-12">
        <div class="content">
        <div class="row">
          <h1>Bill</h1>
          <h3>Edit: <strong><%= @invoice.name_associated %></strong></h3>
          <hr>                    
          </div>
          <%= semantic_form_for @invoice do |f| %>
          <%= f.input :kind_operation, :as => :select, :collection => Invoice.kind_operations.keys.to_a %>
          <%= f.input :kind_payment, :as => :select, :collection => Invoice.kind_payments.keys.to_a  %>
          <%= f.input :kind_invoice, :as => :select, :collection => Invoice.kind_invoices.keys.to_a  %>
          <%= f.input :product %>
          <%= f.input :associated %>
          <%= f.input :quantity %>
          <%= f.input :date %>
          <%= f.input :document %>
          <%= f.input :payment_proof %>
          <%= f.submit :class => "btn btn-primary" %> 
          <%= link_to "Cancel", "/invoices", :class => 'btn btn-success' %>
          
          <% end %>          
        </div>
    </div>
  </div>
</div>
</div>

app/views/invoices/index.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Bills</h1>
                  
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Operation</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                 
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @invoices.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_operation %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/purchases.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Purchases</h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @purchases.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/purchases_cash.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Purchases: <strong>Cash</strong></h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @purchases.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/purchases_credit.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Purchases: <strong>Credits</strong></h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @purchases.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/purchases_draft.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Purchases: <strong>Drafts</strong></h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @purchases.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/purchases_legal.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Purchases: <strong>Invoices</strong></h1>
                   
             <hr>                    
            </div>
           <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @purchases.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/sales.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Sales</h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @sales.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/sales_cash.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Sales: <strong>Cash</strong></h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @sales.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/sales_credit.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Sales: <strong>Credits</strong></h1>
                   
             <hr>                    
            </div>
           <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @sales.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/sales_draft.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Sales: <strong>Drafts</strong></h1>
                   
             <hr>                    
            </div>
           <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>
                    <th>Total</th>                    
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @sales.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    

app/views/invoices/sales_legal.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Sales: <strong>Invoices</strong></h1>
                   
             <hr>                    
            </div>
            <%= render 'layouts/invoices' %>
            <br><br>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Payment</th>
                    <th>Invoice</th>
                    <th>Product</th>   
                    <th>Total</th>        
                    <th>Date</th>                    
                    <th>Associated</th>                    
                    <th>Details</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @sales.each_with_index do |invoice, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= invoice.kind_payment %></td>
                      <td><%= invoice.kind_invoice %></td>
                      <td><%= invoice.name_product %></td>
                      <td><%= invoice.total %></td>
                      <td><%= invoice.date %></td>
                      <td><%= invoice.name_associated %></td>
                      <td><%= link_to  "Details", invoice_path(invoice), :class => 'btn btn-default' %></td>
                      <td><%= link_to  "Edit", edit_invoice_path(invoice), :class => 'btn btn-primary' %></td>
                      <td><%= link_to 'Delete', invoice, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>    