config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  
  resources :products

  devise_for :users
  resources :users, only: [:index, :show]

  resources :invoices
    get 'sales' => 'invoices#sales'
    get 'sales/draft' => 'invoices#sales_draft'
    get 'sales/legal' => 'invoices#sales_legal'
    get 'sales/cash' => 'invoices#sales_cash'
    get 'sales/credit' => 'invoices#sales_credit'
    post 'sales/sale' => 'invoices#sale'

    get 'purchases' => 'invoices#purchases'
    get 'purchases/draft' => 'invoices#purchases_draft'
    get 'purchases/legal' => 'invoices#purchases_legal'
    get 'purchases/cash' => 'invoices#purchases_cash'
    get 'purchases/credit' => 'invoices#purchases_credit'    
    
  resources :associateds do
    resources :invoices
  end
    get 'customers' => 'associateds#customers'
    get 'customers/recurrent' => 'associateds#customers_recurrent'
    get 'customers/punctual' => 'associateds#customers_punctual'
    get 'customers/active' => 'associateds#customers_active'
    get 'customers/inactive' => 'associateds#customers_inactive'
    get 'providers' => 'associateds#providers'
    get 'providers/recurrent' => 'associateds#providers_recurrent'
    get 'providers/punctual' => 'associateds#providers_punctual'
    get 'providers/active' => 'associateds#providers_active'
    get 'providers/inactive' => 'associateds#providers_inactive'
    get 'sponsors' => 'associateds#sponsors'
    get 'sponsors/recurrent' => 'associateds#sponsors_recurrent'
    get 'sponsors/punctual' => 'associateds#sponsors_punctual'
    get 'sponsors/active' => 'associateds#sponsors_active'
    get 'sponsors/inactive' => 'associateds#sponsors_inactive'

    

  
  

end

app/models/associated.rb
class Associated < ActiveRecord::Base
  belongs_to :user
  has_many :invoices, dependent: :destroy
  validates :name, :ci_rif, :alias,:email, :phone, :address, :description, presence: true
  validates :kind, inclusion: { in: :kind }
  validates :status, inclusion: { in: :status }
  validates :frequency, inclusion: { in: :frequency }
  enum kind: [ :Customer, :Sponsor, :Provider ]
	enum status: [ :Active, :Inactive ]
	enum frequency: [ :Recurrent, :Punctual ]
end

app/controllers/associateds_controller.rb
class AssociatedsController < ApplicationController
	before_filter :authenticate_user!

  def index
  	@associateds = Associated.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
    @associated = Associated.includes(:invoices).find(params[:id])
  end

  def new
    @associated = Associated.new   
  end

  def create
    @associated = Associated.new(permit)
    if @associated.save
      redirect_to associateds_path, :notice => 'Associated Successfully Added.'
    else
      render 'new'
    end
  end 

  def edit
    @associated = Associated.find(params[:id])
  end

  def update
    @associated = Associated.find(params[:id])
    if @associated.update(permit)
      redirect_to associateds_path, :notice => 'Associated Successfully Updated.'
    else
      render 'edit'
    end
  end 

  def destroy    
    if Associated.find(params[:id]).destroy
      redirect_to associateds_path, :alert => 'Associated Successfully Deleted.'
    else
      render 'destroy'
    end 
  end  

  def customers 
    @customers = Associated.where(kind: 0)
  end

  def customers_recurrent 
    @customers_recurrent = Associated.where(kind: 0, frequency: 0)
  end

  def customers_punctual 
    @customers_punctual = Associated.where(kind: 0, frequency: 1)
  end

  def customers_active 
    @customers_active = Associated.where(kind: 0, status: 0)
  end

  def customers_inactive 
    @customers_inactive = Associated.where(kind: 0, status: 1)
  end

  def sponsors 
    @sponsors = Associated.where(kind: 1)
  end

  def sponsors_recurrent 
    @sponsors_recurrent = Associated.where(kind: 1, frequency: 0)
  end

  def sponsors_punctual 
    @sponsors_punctual = Associated.where(kind: 1, frequency: 1)
  end

  def sponsors_active 
    @sponsors_active = Associated.where(kind: 1, status: 0)
  end

  def sponsors_inactive 
    @sponsors_inactive = Associated.where(kind: 1, status: 1)
  end

  def providers 
    @providers = Associated.where(kind: 2)
  end

  def providers_recurrent 
    @providers_recurrent = Associated.where(kind: 2, frequency: 0)
  end

  def providers_punctual 
    @providers_punctual = Associated.where(kind: 2, frequency: 1)
  end

  def providers_active 
    @providers_active = Associated.where(kind: 2, status: 0)
  end

  def providers_inactive 
    @providers_inactive = Associated.where(kind: 2, status: 1)
  end

  private

  def permit
  	params.require(:associated).permit(:name, :ci_rif, :alias, :email, :phone, :address, :kind, :frequency,
  								:description, :status, :user_id)
  end
end

app/helpers/associateds_helper.rb
module AssociatedsHelper
end

app/views/associateds/customers_active.html.erb
      <div id="page-content-wrapper">
        <div class="page-content inset">
          <div class="row">
              <div class="col-md-12">
                <div class="content">
                <div class="row">
                  <h1>Customers: <strong>Actives</strong></h1>   
                  <hr>                    
                  </div>
                   <%= render 'layouts/stakeholders' %>
                  <br><br>
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead>
                        <th>N°</th>
                        <th>Name</th>
                        <th>CI-RIF</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Details</th>
                        <th>Update</th>
                        <th>Delete</th>
                      </thead>
                      <tbody>
                        <% @customers_active.each_with_index do |associated, index| %>
                        <tr>
                          <td><%= index + 1 %></td>
                          <td><%= associated.name %></td>
                          <td><%= associated.ci_rif %></td>
                          <td><%= associated.email %></td>
                          <td><%= associated.phone %></td>
                          <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                          <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                          <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>                  
                </div> 
            </div>
          </div>
        </div>
      </div>      

app/views/associateds/customers_inactive.html.erb
      <div id="page-content-wrapper">
        <div class="page-content inset">
          <div class="row">
              <div class="col-md-12">
                <div class="content">
                <div class="row">
                  <h1>Customers: <strong>Inactives</strong></h1> 
                  <hr>                    
                  </div>
                   <%= render 'layouts/stakeholders' %>
                  <br><br>
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead>
                        <th>N°</th>
                        <th>Name</th>
                        <th>CI-RIF</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Details</th>
                        <th>Update</th>
                        <th>Delete</th>
                      </thead>
                      <tbody>
                        <% @customers_inactive.each_with_index do |associated, index| %>
                        <tr>
                          <td><%= index + 1 %></td>
                          <td><%= associated.name %></td>
                          <td><%= associated.ci_rif %></td>
                          <td><%= associated.email %></td>
                          <td><%= associated.phone %></td>
                          <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                          <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                          <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>                  
                </div> 
            </div>
          </div>
        </div>
      </div>      

app/views/associateds/customers_recurrent.html.erb
      <div id="page-content-wrapper">
        <div class="page-content inset">
          <div class="row">
              <div class="col-md-12">
                <div class="content">
                <div class="row">
                  <h1>Customers: <strong>Recurrents</strong></h1> 
                  <hr>                    
                  </div>
                   <%= render 'layouts/stakeholders' %>
                  <br><br>
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead>
                        <th>N°</th>
                        <th>Name</th>
                        <th>CI-RIF</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Details</th>
                        <th>Update</th>
                        <th>Delete</th>
                      </thead>
                      <tbody>
                        <% @customers_recurrent.each_with_index do |associated, index| %>
                        <tr>
                          <td><%= index + 1 %></td>
                          <td><%= associated.name %></td>
                          <td><%= associated.ci_rif %></td>
                          <td><%= associated.email %></td>
                          <td><%= associated.phone %></td>
                          <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                          <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                          <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                        </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>                  
                </div> 
            </div>
          </div>
        </div>
      </div>      

app/views/associateds/edit.html.erb
 <div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Stakeholders</h1>
            <h3><strong>Edit <%= @associated.kind %>:</strong> </strong><%= @associated.name %></h3>
            <hr>                    
            </div>
            <%= semantic_form_for @associated do |f| %>
            <%= f.input :name %>
            <%= f.input :ci_rif %>
            <%= f.input :alias %>
            <%= f.input :email %>
            <%= f.input :phone %>
            <%= f.input :address %>
            <%= f.input :kind, :as => :select, :collection => Associated.kinds.keys.to_a %>
            <%= f.input :frequency, :as => :select, :collection => Associated.frequencies.keys.to_a %>
            <%= f.input :status, :as => :select, :collection => Associated.statuses.keys.to_a %>
            <%= f.input :description %>
            <%= f.submit :class => "btn btn-primary" %> 
            <%= link_to "Cancel", "/associateds", :class => 'btn btn-success' %>                   
            <% end %>          
          </div>
      </div>
    </div>
  </div>

app/views/associateds/index.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
      <div class="col-md-12">
        <div class="content">
          <div class="row">
            <h1>Stakeholders</h1>
            <hr>
          </div>
           <%= render 'layouts/stakeholders' %>
          <br><br>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <th>N°</th>
                <th>Name</th>
                <th>CI-RIF</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Details</th>
                <th>Update</th>
                <th>Delete</th>
              </thead>
              <tbody>
                <% @associateds.each_with_index do |associated, index| %>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= associated.name %></td>
                  <td><%= associated.ci_rif %></td>
                  <td><%= associated.email %></td>
                  <td><%= associated.phone %></td>
                  <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                  <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                  <td><%= link_to 'Delete', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          
    <%= paginate(@associateds) %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/associateds/providers.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">                
            <div class="row">
            <h1>Providers</h1>  
            <hr>                    
            </div> 
                 <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @providers.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/providers_inactive.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">                
            <div class="row">
            <h1>Providers: <strong>Inactives</strong></h1>  
            <hr>                    
            </div> 
                <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @providers_inactive.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/providers_punctual.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">                
            <div class="row">
            <h1>Providers: <strong>Punctual</strong></h1>  
            <hr>                    
            </div> 
                 <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @providers_punctual.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/providers_recurrent.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">                
            <div class="row">
            <h1>Providers: <strong>Recurrents</strong></h1>  
            <hr>                    
            </div> 
                 <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @providers_recurrent.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/show.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
      <div class="col-md-12">
        <div class="content">
          <div class="row">
            
            <h1><%= @associated.kind %> : <strong><%= @associated.name %></strong></h1>
            <hr>
          </div>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <th>Name</th>
                <th>CI-RIF</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Type</th>
                <th>Frequency</th>
                <th>Description</th>
              </thead>
              <tbody>
                <tr>
                  <td><%= @associated.name %></td>
                  <td><%= @associated.ci_rif %></td>
                  <td><%= @associated.email %></td>
                  <td><%= @associated.phone %></td>
                  <td><%= @associated.address %></td>
                  <td><%= @associated.kind %></td>
                  <td><%= @associated.frequency %></td>
                  <td><%= @associated.description %></td>
                </tr>
              </tbody>
            </table>
          </div>
          <% @associated.invoices.each_with_index do |invoice, index| %>
          <h4><strong><%= invoice.kind_invoice %> # <%= invoice.id %></strong></h4>
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <th>N°</th>
                <th>Type</th>
                <th>Payment</th>
                <th>Invoice</th>
                <th>Product</th>
                <th>Description</th>
                <th>Price</th>
                <th>Tax</th>
                <th>Total</th>
                <th>Date</th>
              </thead>
              <tbody>
                <tr>
                  <td><%= index + 1 %></td>
                  <td><%= invoice.kind_operation %></td>
                  <td><%= invoice.kind_payment %></td>
                  <td><%= invoice.kind_invoice %></td>
                  <td><%= invoice.name_product %></td>
                  <td><%= invoice.description %></td>
                  <td><%= invoice.subtotal %></td>
                  <td><%= invoice.tax %></td>
                  <td><%= invoice.total %></td>
                  <td><%= invoice.date %></td>
                </tr>
              </tbody>
            </table>
          </div>
          <% end %>
          <%= link_to "Return", "/associateds", :class => 'btn btn-mini btn-success' %>
          <%= link_to  "Edit", edit_associated_path(@associated), :class => 'btn btn-mini btn-primary' %>
          <%= link_to 'Delete', @associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/associateds/sponsors.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Sponsors</h1>   
            <hr>                    
            </div>
             <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @sponsors.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/sponsors_inactive.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Sponsors <strong>Inactives</strong></h1>   
            <hr>                    
            </div>
             <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @sponsors_inactive.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/sponsors_punctual.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Sponsors: <strong>Punctual</strong></h1>   
            <hr>                    
            </div>
             <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @sponsors_punctual.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      

app/views/associateds/sponsors_recurrent.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Sponsors: <strong>Recurrents</strong></h1>
            <hr>                    
            </div>
             <%= render 'layouts/stakeholders' %>
            <br><br>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>N°</th>
                  <th>Name</th>
                  <th>CI-RIF</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th>Details</th>
                  <th>Update</th>
                  <th>Delete</th>
                </thead>
                <tbody>
                  <% @sponsors_recurrent.each_with_index do |associated, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= associated.name %></td>
                    <td><%= associated.ci_rif %></td>
                    <td><%= associated.email %></td>
                    <td><%= associated.phone %></td>
                    <td><%= link_to  "Details", associated_path(associated), :class => 'btn btn-mini btn-default' %></td>
                    <td><%= link_to  "Edit", edit_associated_path(associated), :class => 'btn btn-mini btn-primary' %></td>
                    <td><%= link_to 'Destroy', associated, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>                  
          </div> 
      </div>
    </div>
  </div>
</div>      