config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  
  resources :products

  devise_for :users
  resources :users, only: [:index, :show]

  resources :invoices
    get 'sales' => 'invoices#sales'
    get 'sales/draft' => 'invoices#sales_draft'
    get 'sales/legal' => 'invoices#sales_legal'
    get 'sales/cash' => 'invoices#sales_cash'
    get 'sales/credit' => 'invoices#sales_credit'
    post 'sales/sale' => 'invoices#sale'

    get 'purchases' => 'invoices#purchases'
    get 'purchases/draft' => 'invoices#purchases_draft'
    get 'purchases/legal' => 'invoices#purchases_legal'
    get 'purchases/cash' => 'invoices#purchases_cash'
    get 'purchases/credit' => 'invoices#purchases_credit'    
    
  resources :associateds do
    resources :invoices
  end
    get 'customers' => 'associateds#customers'
    get 'customers/recurrent' => 'associateds#customers_recurrent'
    get 'customers/punctual' => 'associateds#customers_punctual'
    get 'customers/active' => 'associateds#customers_active'
    get 'customers/inactive' => 'associateds#customers_inactive'
    get 'providers' => 'associateds#providers'
    get 'providers/recurrent' => 'associateds#providers_recurrent'
    get 'providers/punctual' => 'associateds#providers_punctual'
    get 'providers/active' => 'associateds#providers_active'
    get 'providers/inactive' => 'associateds#providers_inactive'
    get 'sponsors' => 'associateds#sponsors'
    get 'sponsors/recurrent' => 'associateds#sponsors_recurrent'
    get 'sponsors/punctual' => 'associateds#sponsors_punctual'
    get 'sponsors/active' => 'associateds#sponsors_active'
    get 'sponsors/inactive' => 'associateds#sponsors_inactive'

    

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :invoice, dependent: :destroy
  validates :name, :price, presence: true
  validates :name, length: { maximum: 30 }
  validates :description, length: { maximum: 150 }
  validates :price, length: { maximum: 10 }  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @products = Product.all 
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new   
  end

  def create
    @product = Product.new(permit)
    if @product.save
      redirect_to products_path, :notice => 'Product Successfully Added.'
    else
      render 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(permit)
      redirect_to products_path, :notice => 'Product Successfully Updated.'
    else
      render 'edit'
    end
  end

  def destroy    
    if Product.find(params[:id]).destroy
      redirect_to products_path, :alert => 'Product Successfully Deleted.'
    else
      render 'destroy'
    end 
  end    

  private
  def permit
    params.require(:product).permit(:name, :description, :price, :date, :quantity, :user_id, :invoice_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div id="page-content-wrapper">
<div class="page-content inset">
  <div class="row">
      <div class="col-md-12">
        <div class="content">
        <div class="row">
          <h1>Product</h1>
          <h3>Edit: <strong><%= @product.name %></strong></h3>
          <hr>                    
          </div>
          <%= semantic_form_for @product do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.submit :class => "btn btn-primary" %> 
          <%= link_to "Cancel", "/products", :class => 'btn btn-success' %>
          
          <% end %>          
        </div>
    </div>
  </div>
</div>
</div>

app/views/products/index.html.erb
 
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
            <div class="row">
            <h1>Products</h1>
               <%= link_to "New Product", new_product_path, :class => 'btn btn-mini btn-success' %>    
             <hr>                    
            </div>
              <div class="table-responsive">
                <table class="table table-hover">
                  <thead>
                    <th>N°</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Update</th>
                    <th>Delete</th>
                  </thead>
                  <tbody>
                    <% @products.each_with_index do |product, index| %>
                    <tr>
                      <td><%= index + 1 %></td>
                      <td><%= product.name %></td>
                      <td><%= product.description %></td>
                      <td><%= product.price %></td>
                      <td><%= link_to  "Details", product_path(product), :class => 'btn btn-info' %></td>
                      <td><%= link_to  "Edit", edit_product_path(product), :class => 'btn btn-primary' %></td>
                      <td><%= link_to "Delete", product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>                  
          </div> 
      </div>
    </div>
  </div>


<div class="modal-dialog fade" role="document" id="my-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Delete</h4>
    </div>
    <div class="modal-body">
      <h3>Are you sure?</h3>
    </div>
    <div class="modal-footer">
      <%= button_to "Delete", products_path(@products), method: :delete, :class => 'btn btn-danger' %>
    </div>
  </div>
</div>   

app/views/products/new.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>New Product</h1>
            <hr>                    
            </div>
            <%= semantic_form_for @product do |f| %>
            <%= f.input :name %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.submit :class => "btn btn-primary" %> 
            <%= link_to "Cancel", "/products", :class => 'btn btn-success' %> <% end %>         
          </div>
      </div>
    </div>
  </div>
</div>     

app/views/products/show.html.erb
<div id="page-content-wrapper">
  <div class="page-content inset">
    <div class="row">
        <div class="col-md-12">
          <div class="content">
          <div class="row">
            <h1>Product: <strong><%= @product.name %></strong></h1>
             <hr>  
            </div>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <th>Name</th>
                  <th>Description</th>
                  <th>Price</th>
                </thead>
                <tbody>                        
                  <tr>
                    <td><%= @product.name %></td>
                    <td><%= @product.description %></td>
                    <td><%= @product.price %></td>
                  </tr>
                </tbody>
              </table>
            </div>  
            <%= link_to "Return", "/products", :class => 'btn btn-mini btn-success' %>    <%= link_to  "Edit", edit_product_path(@product), :class => 'btn btn-primary' %>
            <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %>       
          </div>
      </div>
    </div>
  </div>
</div>      