config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  
  resources :products

  devise_for :users
  resources :users, only: [:index, :show]

  resources :invoices
    get 'sales' => 'invoices#sales'
    get 'sales/draft' => 'invoices#sales_draft'
    get 'sales/legal' => 'invoices#sales_legal'
    get 'sales/cash' => 'invoices#sales_cash'
    get 'sales/credit' => 'invoices#sales_credit'
    post 'sales/sale' => 'invoices#sale'

    get 'purchases' => 'invoices#purchases'
    get 'purchases/draft' => 'invoices#purchases_draft'
    get 'purchases/legal' => 'invoices#purchases_legal'
    get 'purchases/cash' => 'invoices#purchases_cash'
    get 'purchases/credit' => 'invoices#purchases_credit'    
    
  resources :associateds do
    resources :invoices
  end
    get 'customers' => 'associateds#customers'
    get 'customers/recurrent' => 'associateds#customers_recurrent'
    get 'customers/punctual' => 'associateds#customers_punctual'
    get 'customers/active' => 'associateds#customers_active'
    get 'customers/inactive' => 'associateds#customers_inactive'
    get 'providers' => 'associateds#providers'
    get 'providers/recurrent' => 'associateds#providers_recurrent'
    get 'providers/punctual' => 'associateds#providers_punctual'
    get 'providers/active' => 'associateds#providers_active'
    get 'providers/inactive' => 'associateds#providers_inactive'
    get 'sponsors' => 'associateds#sponsors'
    get 'sponsors/recurrent' => 'associateds#sponsors_recurrent'
    get 'sponsors/punctual' => 'associateds#sponsors_punctual'
    get 'sponsors/active' => 'associateds#sponsors_active'
    get 'sponsors/inactive' => 'associateds#sponsors_inactive'

    

  
  

end

app/views/layouts/_invoices.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Bills", Invoice %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sales <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li role="presentation"><%= link_to "Sales", sales_path %></li>
      <li class="divider"></li>      
      <li role="presentation"><%= link_to "Draft", sales_draft_path %></li>
      <li role="presentation"><%= link_to "Legal", sales_legal_path %></li>
      <li role="presentation"><%= link_to "Cash", sales_cash_path %></li>
      <li role="presentation"><%= link_to "Credit", sales_credit_path %></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Purchases <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li role="presentation"><%= link_to "Purchases", purchases_path %></li>
      <li class="divider"></li>      
      <li role="presentation"><%= link_to "Draft", purchases_draft_path %></li>
      <li role="presentation"><%= link_to "Legal", purchases_legal_path %></li>
      <li role="presentation"><%= link_to "Cash", purchases_cash_path %></li>
      <li role="presentation"><%= link_to "Credit", purchases_credit_path %></li>
    </ul>
  </li>  
  <li><%= link_to "New Bill", new_invoice_path, :class => 'btn btn-mini btn-info' %></li>
</ul>

app/views/layouts/_stakeholders.html.erb
<ul class="nav nav-tabs">
  <li role="presentation"><%= link_to "Stakeholders", Associated %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Customers <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li role="presentation"><%= link_to "Customers", customers_path %></li>
      <li class="divider"></li>
      <li role="presentation"><%= link_to "Actives", customers_active_path %></li>
      <li role="presentation"><%= link_to "Inactives", customers_inactive_path %></li>
      <li role="presentation"><%= link_to "Punctuals", customers_punctual_path %></li>
      <li role="presentation"><%= link_to "Recurrents", customers_recurrent_path %></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sponsors <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li role="presentation"><%= link_to "Sponsors", sponsors_path %></li>
      <li class="divider"></li>
      <li role="presentation"><%= link_to "Actives", sponsors_active_path %></li>
      <li role="presentation"><%= link_to "Inactives", sponsors_inactive_path %></li>
      <li role="presentation"><%= link_to "Punctuals", sponsors_punctual_path %></li>
      <li role="presentation"><%= link_to "Recurrents", sponsors_recurrent_path %></li>
    </ul>
  </li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Providers <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li role="presentation"><%= link_to "Providers", providers_path %></li>
      <li class="divider"></li>
      <li role="presentation"><%= link_to "Actives", sponsors_active_path %></li>
      <li role="presentation"><%= link_to "Inactives", sponsors_inactive_path %></li>
      <li role="presentation"><%= link_to "Punctuals", sponsors_punctual_path %></li>
      <li role="presentation"><%= link_to "Recurrents", sponsors_recurrent_path %></li>
    </ul>
  </li>
  <li><%= link_to "New Associated", new_associated_path, :class => 'btn btn-mini btn-info' %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackFacturation</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://i.icomoon.io/public/temp/2fd34eb3c2/UntitledProject/style.css">
</head>
<body>

     <div id="wrapper" class="active">
          <div id="sidebar-wrapper">
            <ul id="sidebar_menu" class="sidebar-nav">
                 <%= image_tag "full-logo-aeb6cec9ca9eee43393c56f9d220e49c.png", :alt => "logo", :title => "logo"%>
            </ul>
              <ul class="sidebar-nav" id="sidebar">     
                <li><a><%= link_to  "Stakeholders",Associated %></a></li>
                <li><a><%= link_to  "Products",Product %></a></li>
                <li><a><%= link_to  "Bills",Invoice %></a></li>                
                <li><a><%= link_to  "Users",User %></a></li>
              </ul>
              <br><br>
              <footer>
                <p>&copy; Hack 2015</p>
              </footer>
          </div>          
          <!-- Page content -->
          <div id="page-content-wrapper">
            <div class="page-content inset">
              <div class="row">
                  <div class="col-md-12">
                  
                      <nav class="navbar navbar-default">
                        <div class="container-fluid">
                          <div class="navbar-header navbar-right">
                            <p class="navbar-text pull-right" style="margin-right:50px;">
                              <% if user_signed_in? %>
                              <strong><%= current_user.username %></strong>.
                              <%= link_to 'Edit', edit_user_registration_path %> |
                              <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                              <% else %>
                              <%= link_to "Sign up", new_user_registration_path  %> |
                              <%= link_to "Login", new_user_session_path  %>
                              <% end %>
                              </p>
                          </div>
                        </div>
                      </nav>  
                        <%= bootstrap_flash %>            
                        <%= yield %>     
                  
                </div>
              </div>
            </div>
          </div>      
      </div>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BackFacturacion" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>



  </body>
</html>